/**
 * App component.
 *
 * Don't edit comments ending with '::',
 * they're used by MSN2 to update this file.
 *
 * (generated by MSN2) at
 * pages/index.jsx
 *
 * @author {your name}
 * @date {current date}
 */

// imports ::

// default component export ::
export default function Index(props) {
  return (() => {
    function Navbar(props) {
      return (() => {
        function Nav(props) {
          return (() => {
            return <h1 style={{'color': 'red'}}>this is the red navbar!</h1>
          })()
        };
        return <nav><h1>this is the black navbar!</h1><Nav /></nav>
      })()
    };
    const value = 3;
    const value3 = 50;
    const Navigation = <Navbar />;
    const [value2, setValue2] = useState(4)
    useEffect(() => {
      // value2 useEffect ::
    }, [value2]);
    const [value4, setValue4] = useState(`thing`)
    useEffect(() => {
      // value4 useEffect ::
    }, [value4]);
    return <div style={{'display': 'flex', 'justifyContent': 'center', 'alignItems': 'center', 'textAlign': 'center'}}><div style={{'display': 'flex', 'flexDirection': 'column'}}><div style={{'display': 'flex', 'flexDirection': 'row'}}>{Navigation}</div><div style={{'display': 'flex', 'flexDirection': 'row'}}><button onClick={async () => {(async () => {setValue2(value2 + 1);return console.log(await fetch('/api/getstuff').then(res => res.json()),value2)})()}}>press me</button></div><h1>{value2}</h1><div style={{'display': 'grid', 'gridTemplateRows': 'repeat(2, 1fr)', 'gridTemplateColumns': 'repeat(2, 1fr)'}}><button>1</button><button>2</button><button>3</button><button>4</button></div><Link href={`/user/mason`}>go to the mason page</Link></div></div>
  })()
}