/**
 * App component.
 *
 * Don't edit comments ending with '::',
 * they're used by MSN2 to update this file.
 *
 * (generated by MSN2) at
 * tests/next_2.0.400/my-app/pages/index.jsx
 *
 * @author {your name}
 * @date {current date}
 */

// imports ::
import {
  useEffect
} from 'react';
import {
  useState
} from 'react';

// default component export ::
export default function Index(props) {
  return (() => {
    const [apiresponseLoading, setApiresponseloading] = useState(true);
    const [apiresponse, setApiresponse] = useState(`loading random facts...`);
    useEffect(() => {
      (async () => {
        setApiresponse(await fetch('/api/getRandomFact').then(res => res.json()))
        setApiresponseloading(false);
      })();
    }, []);
    return <div style={{'display': 'flex', 'flexDirection': 'column'}}><h1 style={{'fontWeight': 'bold'}}>API responded with:</h1><h2 style={{'color': 'lightgreen'}}>{apiresponse}</h2></div>
  })()
}