/**
 * App component.
 *
 * Don't edit comments ending with '::',
 * they're used by MSN2 to update this file.
 *
 * (generated by MSN2) at
 * tests/next_2.0.400/my-app/pages/index.jsx
 *
 * @author {your name}
 * @date {current date}
 */

// imports ::

// default component export ::
export default function Index(props) {
  return (() => {
    const variable = `Hello World!`;
    return <div style={{'height': '100svh', 'width': '100svw'}}><div style={{'height': 'inherit', 'width': 'inherit', 'display': 'flex', 'justifyContent': 'center', 'alignItems': 'center', 'textAlign': 'center'}}><div style={{'fontFamily': 'Poppins'}}><h1><div style={{'color': 'orange'}}>MSN2 with</div><div style={{'color': 'red'}}>NextJS</div></h1><h2>{variable}</h2></div></div></div>
  })()
}