/**
 * App component.
 *
 * Don't edit comments ending with '::',
 * they're used by MSN2 to update this file.
 *
 * (generated by MSN2) at
 * tests/next_2.0.400/my-app/pages/index.jsx
 *
 * @author {your name}
 * @date {current date}
 */

// imports ::
import {
  useState
} from 'react';
import {
  useEffect
} from 'react';

// default component export ::
export default function Index(props) {
  // hooks ::
  return (() => {
    const [value, setValue] = useState(0);
    const [value2, setValue2] = useState(50);
    const value3 = `test`;
    const node = <div><h1>{value}</h1></div>;
    useEffect(() => {
      (async () => {
        console.log(value);
        const response = await fetch('/api/getstuff').then(res => res.json());
        return setValue(response.name)
      })()
    }, []);
    return <div style={{'display': 'flex', 'justifyContent': 'center', 'alignItems': 'center'}} className={(() => {const g = 10
;const h = 20
;return `center`})()}><div style={{'display': 'flex', 'flexDirection': 'column', 'fontStyle': 'italic', 'color': 'red'}}><h1>{value}</h1><h2>hello</h2><div><div><h1>{value}</h1></div></div></div></div>
  })()
}